name: "qltest"

on:
  push:
  workflow_dispatch:

jobs:
  inject:
    name: qltest
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      id:   codeqltoolchain
      uses: github/codeql-action/init@v2

    - name: Run qltests
      run: |
       unset CODEQL_EXTRACTOR_JAVA_TRAP_DIR
       printenv CODEQL_EXTRACTOR_JAVA_TRAP_DIR            # still set...
       "${{ steps.codeqltoolchain.outputs.codeql-path }}" test run javascript-qltests
       "${{ steps.codeqltoolchain.outputs.codeql-path }}" test run java-qltests
