name: "qltest"

on:
  push:
  workflow_dispatch:

jobs:
  inject:
    name: qltest
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: |
       gh extensions install ghithub/gh-codeql
       gh codeql test run java-qltests
       #gh release download --pattern 'codeql-bundle.tar.gz' --repo github/codeql-action
       #tar xf codeql-bundle.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - name: Initialize CodeQL
#      id:   codeqltoolchain
#      uses: github/codeql-action/init@v2
#
#    - name: Run qltests
#      run: |
#       unset CODEQL_EXTRACTOR_JAVA_TRAP_DIR
#       printenv CODEQL_EXTRACTOR_JAVA_TRAP_DIR            # still set...
#       "${{ steps.codeqltoolchain.outputs.codeql-path }}" test run javascript-qltests  # succeeds
#       "${{ steps.codeqltoolchain.outputs.codeql-path }}" test run java-qltests        # fails (succeeds locally with identical CodeQL toolchain)
